spring.application.name=screenmatch

#spring.profiles.active=dev-demo
#spring.profiles.active=dev-cli
#spring.profiles.active=dev-top5
#spring.profiles.active=dev-top5-pretty
#spring.profiles.active=dev-episodios-por-anio
spring.profiles.active=dev-busqueda-parcial